# Mushroom Edibility Prediction

## Imports

In [3]:
import torch
from torch import nn #This is to build the neural networks
from torch.utils.data import Dataset, DataLoader #Data loader object
import numpy as np #for array operations.
import pandas as pd
from torch.optim import Adam #This is for optimizer.
from sklearn.model_selection import train_test_split #to split the data

from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve # scores

import matplotlib.pyplot as plt
import seaborn as sns #these are for viewing.

from scipy import stats #for statistics.


## Data Preprocessing

In [4]:
mushroom = pd.read_csv("mushrooms.csv", delimiter=",")
mushroom.head(5)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [5]:
mushroom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [6]:
print(mushroom["class"].value_counts())

class
e    4208
p    3916
Name: count, dtype: int64


In [7]:
a = mushroom.describe()[1:2]
a = a.transpose()
display(a) #as we can see the veil-type is irrelevant because it has only a value

a["unique"].sum()

unique
class                         2
cap-shape                     6
cap-surface                   4
cap-color                    10
bruises                       2
odor                          9
gill-attachment               2
gill-spacing                  2
gill-size                     2
gill-color                   12
stalk-shape                   2
stalk-root                    5
stalk-surface-above-ring      4
stalk-surface-below-ring      4
stalk-color-above-ring        9
stalk-color-below-ring        9
veil-type                     1
veil-color                    4
ring-number                   3
ring-type                     5
spore-print-color             9
population                    6
habitat                       7

119

In [8]:
Y = mushroom["class"]
X = mushroom.drop(columns="class")
display("DATA before one-hot ecnoding:")
display(X)
X = pd.get_dummies(data = X, prefix=[column for column in X.columns], dtype=float)
display("DATA after one-hot ecnoding:")
display(X)

'DATA before one-hot ecnoding:'

cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-type veil-color ring-number ring-type spore-print-color population  \
0            p          w           o         p                 k          s   
1            p          w           o         p                 n          n   
2            p          w           o         p                 n          n   
3            p          w           o         p                 k          s   
4            p          w           o         e                 n          a   
...        ...        ...         ...       ...               ...        ...   
8119         p          o           o         p                 b          c   
8120         p          n           o         p                 b          v   
8121         p          o           o         p                 b          c   
8122         p          w           o         e                 w          v   
8123         p          o           o         p                 o          c   

     habitat  
0          u  
1          g  
2          m  
3          u  
4          g  
...      ...  
8119       l  
8120       l  
8121       l  
8122       l  
8123       l  

[8124 rows x 22 columns]

'DATA after one-hot ecnoding:'

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0             0.0          0.0          0.0          0.0          0.0   
1             0.0          0.0          0.0          0.0          0.0   
2             1.0          0.0          0.0          0.0          0.0   
3             0.0          0.0          0.0          0.0          0.0   
4             0.0          0.0          0.0          0.0          0.0   
...           ...          ...          ...          ...          ...   
8119          0.0          0.0          0.0          1.0          0.0   
8120          0.0          0.0          0.0          0.0          0.0   
8121          0.0          0.0          1.0          0.0          0.0   
8122          0.0          0.0          0.0          1.0          0.0   
8123          0.0          0.0          0.0          0.0          0.0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0             1.0            0.0            0.0            1.0            0.0   
1             1.0            0.0            0.0            1.0            0.0   
2             0.0            0.0            0.0            1.0            0.0   
3             1.0            0.0            0.0            0.0            1.0   
4             1.0            0.0            0.0            1.0            0.0   
...           ...            ...            ...            ...            ...   
8119          0.0            0.0            0.0            1.0            0.0   
8120          1.0            0.0            0.0            1.0            0.0   
8121          0.0            0.0            0.0            1.0            0.0   
8122          0.0            0.0            0.0            0.0            1.0   
8123          1.0            0.0            0.0            1.0            0.0   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0     ...           1.0           0.0           0.0        0.0        0.0   
1     ...           0.0           0.0           0.0        0.0        1.0   
2     ...           0.0           0.0           0.0        0.0        0.0   
3     ...           1.0           0.0           0.0        0.0        0.0   
4     ...           0.0           0.0           0.0        0.0        1.0   
...   ...           ...           ...           ...        ...        ...   
8119  ...           0.0           0.0           0.0        0.0        0.0   
8120  ...           0.0           1.0           0.0        0.0        0.0   
8121  ...           0.0           0.0           0.0        0.0        0.0   
8122  ...           0.0           1.0           0.0        0.0        0.0   
8123  ...           0.0           0.0           0.0        0.0        0.0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0           0.0        0.0        0.0        1.0        0.0  
1           0.0        0.0        0.0        0.0        0.0  
2           0.0        1.0        0.0        0.0        0.0  
3           0.0        0.0        0.0        1.0        0.0  
4           0.0        0.0        0.0        0.0        0.0  
...         ...        ...        ...        ...        ...  
8119        1.0        0.0        0.0        0.0        0.0  
8120        1.0        0.0        0.0        0.0        0.0  
8121        1.0        0.0        0.0        0.0        0.0  
8122        1.0        0.0        0.0        0.0        0.0  
8123        1.0        0.0        0.0        0.0        0.0  

[8124 rows x 117 columns]

In [9]:
#one-hot encoding the target value as well

mapper = {"p" : 1.0, "e":0.0}

Y = Y.map(mapper)
display(Y)

0       1.0
1       0.0
2       0.0
3       1.0
4       0.0
       ... 
8119    0.0
8120    0.0
8121    0.0
8122    1.0
8123    0.0
Name: class, Length: 8124, dtype: float64

In [10]:
##Train test splitting = 
X = X.to_numpy()
Y = Y.to_numpy()
display(X)
display(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)
X_test, X_val, Y_test, Y_val = train_test_split(X_test, Y_test, test_size = 0.5)

print (X_train.shape)
print (X_val.shape)
print (X_test.shape)

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([1., 0., 0., ..., 0., 1., 0.])

(5686, 117)
(1219, 117)
(1219, 117)


In [11]:
class dataset(Dataset):
    def __init__(self,X, Y):
        self.X = torch.tensor(X, dtype= torch.float32).to(device="mps")
        self.Y = torch.tensor(Y, dtype= torch.float32 ).to(device="mps")

    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, index):
        return self.X[index], self.Y[index]

#you can do the same with TensorDataset which pytorch provides.

train_data = dataset(X_train,Y_train)
test_data = dataset(X_test,Y_test)
validation_data = dataset(X_val,Y_val)
# from torch.utils.data import TensorDataset

#blabla_data = TensorDataset(torch.tensor(X, dtype = torch.float32), torch.tensor(Y, dtype= torch.float32) )
train_data.__getitem__(2)

(tensor([0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
         0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
         0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 1., 0., 0., 0., 0., 0.], device='mps:0'),
 tensor(1., device='mps:0'))

In [12]:
from torch.utils.data import BatchSampler, RandomSampler

In [13]:
def loaders(train, test, val) -> dict[str,any]:
    
    loaders = {"train":train, "test":test, "validation":val}

    for key, val in loaders.items():

        loaders[key] = DataLoader(dataset=val, batch_sampler = 
                                  BatchSampler(
            sampler=RandomSampler(val),
            batch_size=8,
            drop_last=True
            )
        )

    print(loaders)
    return loaders["train"], loaders["test"], loaders["validation"]


In [14]:
train_dataloader, test_dataloader, validation_dataloader = loaders(train=train_data, test=test_data, val=validation_data)


{'train': <torch.utils.data.dataloader.DataLoader object at 0x161c62c90>, 'test': <torch.utils.data.dataloader.DataLoader object at 0x157491430>, 'validation': <torch.utils.data.dataloader.DataLoader object at 0x161c62810>}


In [15]:
for x, y in train_dataloader:
    print(x)
    print("==============")
    print(y)
    break

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
         1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.

## MLP Model

In [31]:
from torchinfo import summary

In [32]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.input_layer = nn.Linear(X.shape[1], 10)
        self.linear = nn.Linear(10, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        x = self.input_layer(x)
        x = self.linear(x)
        x = self.sigmoid(x)
        return x

model = MyModel().to(device="mps")
summary(model, (X.shape[1],))


Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [1]                       --
├─Linear: 1-1                            [10]                      1,180
├─Linear: 1-2                            [1]                       11
├─Sigmoid: 1-3                           [1]                       --
Total params: 1,191
Trainable params: 1,191
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [ ]:
criterian = nn.BCELoss()
optimizer = Adam(model.parameters(), lr= 1e-3)
